pipeline:
#  restore-cache:
#    image: drillster/drone-volume-cache
#    restore: true
#    mount:
#      - ./.yarn-cache
#      - ./node_modules
#    volumes:
#      - /tmp/cache:/cache

publish:
    image: plugins/docker
    repo: eu.gcr.io/pgmtc-net/md-web-client
    tags: [ latest ]
